Update Hungarian translation
AppIntro/AppIntro pull request #1170
Opened 2023-12-11 10:49 UTC by fejese

Adding missing strings

2023-12-11 10:50 UTC, fejese commented
cc @cortinico as per instructions

2023-12-11 13:26 UTC, cortinico requested changes

2023-12-11 13:26 UTC, cortinico commented on appintro/src/main/res/values-hu/strings.xml
> +    <string name="app_intro_image_content_description" tools:ignore="MissingTranslation">GRAFIKA</string>
```suggestion
    <string name="app_intro_next_button">KÖVETKEZŐ</string>
    <string name="app_intro_back_button">VISSZA</string>
    <string name="app_intro_done_button">KÉSZ</string>
    <string name="app_intro_image_content_description">GRAFIKA</string>
```

2023-12-12 04:24 UTC, fejese commented on appintro/src/main/res/values-hu/strings.xml
> +    <string name="app_intro_next_button" tools:ignore="MissingTranslation">KÖVETKEZŐ</string>
```suggestion
    <string name="app_intro_next_button" tools:ignore="MissingTranslation">TOVÁBB</string>
```

2023-12-12 04:26 UTC, fejese commented on appintro/src/main/res/values-hu/strings.xml
> +    <string name="app_intro_next_button">KÖVETKEZŐ</string>
```suggestion
    <string name="app_intro_next_button">TOVVÁBB</string>
```

2023-12-12 04:28 UTC, fejese reviewed
Updated PR as per suggestion as well as improved one of the new translations a bit

2023-12-12 09:31 UTC, cortinico approved these changes

2023-12-12 09:31 UTC, merged