Separate logic from UI layer to core module to be shared between Appintro module and appintro-compose module
AppIntro/AppIntro pull request #1250
Opened 2024-10-26 02:02 UTC by markoeltiger

In Library plan to support compose i have worked on separating modules to a new module which called core for this ticket 
https://github.com/AppIntro/AppIntro/issues/1214

2024-10-29 13:48 UTC, markoeltiger commented
Hello @paolorotolo  , is there any chance to get this merged before end of October?

2024-10-29 14:39 UTC, paolorotolo commented
Hi @markoeltiger, thanks a lot for the contribution! I'm currently traveling for Droidcon London, I'll try to review it in my spare time :)

2024-10-29 14:40 UTC, paolorotolo commented
Meanwhile, could you please address the `KLint` violations?

2024-10-30 04:31 UTC, markoeltiger commented
HI @paolorotolo , wish you safe travels and have a great Droidcon <3 , I did ktlint fixes.

2024-10-30 16:00 UTC, paolorotolo commented on gradle/libs.versions.toml
> +agp = "8.4.1"
Why are we downgrading AGP here?

2024-10-30 16:02 UTC, paolorotolo commented on gradle/libs.versions.toml
> +material = "1.12.0"
I can't find usages of those new dependencies, could you remove them if they're not used please? :)

2024-10-30 16:04 UTC, paolorotolo commented on core/src/main/java/com/appintro/core/utils/TypefaceContainer.kt
>  import android.widget.TextView
`TypefaceContainer` depends on `TextView`. Can you please move this as well in the view-specific module?

2024-10-30 16:06 UTC, paolorotolo commented on core/src/main/java/com/appintro/core/indicator/DotIndicatorController.kt
>  class DotIndicatorController(context: Context) : IndicatorController, LinearLayout(context) {
This `IndicatorController` implementation depends on Views. It should be more suitable for the view-specific module

2024-10-30 16:09 UTC, paolorotolo commented on core/src/main/java/com/appintro/core/indicator/DotIndicatorController.kt
> +    override var selectedIndicatorColor = ContextCompat.getColor(context, com.appintro.core.R.color.appintro_default_selected_color)
Could you `import com.appintro.core.R as CoreR` in those cases, to improve code readibility? 

Ex. `com.appintro.core.R.color.appintro_default_selected_color`
-> `CoreR.color.appintro_default_selected_color`

2024-10-30 16:12 UTC, paolorotolo commented on core/build.gradle.kts
> +    compileSdk = 34
Please use values from Version Catalog here (`libs.versions.compile.sdk.version.get().toInt()`)

2024-11-02 13:37 UTC, markoeltiger commented
Hello @paolorotolo, Your feedback is highly appreciated,thanks a lot for it.
I have worked on your comments what I have done.
-Renamed new module to dev.appintro.core.
-Made sure all view-related files are back.
-used simple import to increase code reliability .
If you have any more comments I am open to work on it .
Thanks alot.

2024-11-10 14:59 UTC, paolorotolo requested changes
Thanks a lot for your changes! Looks very good!
Just some final minor things and it's ready to go! 🚀

2024-11-10 14:59 UTC, paolorotolo commented on core/src/test/java/com/appintro/core/ExampleUnitTest.kt
> +class ExampleUnitTest {
This can be removed, it's causing tests to fail since jUnit is not a dependency anymore

2024-11-10 14:59 UTC, paolorotolo commented on appintro/src/main/java/com/github/appintro/indicator/IndicatorController.kt
Awesome job moving `DotIndicatorController` in the view-dependent module. But I think the interface `IndicatorController` belongs in the common `core` one, since it's generic enough and could be the base for a `ComposeIndicatorController` in the future.

2024-11-10 14:59 UTC, paolorotolo commented on appintro/src/main/java/com/github/appintro/indicator/ProgressIndicatorController.kt
> +package dev.appintro.core.indicator
This is using the wrong package declaration. The file is in `com.github.appintro`

2024-11-13 22:51 UTC, markoeltiger commented
Hello @paolorotolo , I have worked on the minor changes you requested which was fine and great feedback thanks a lot for it , cant wait to work on App intro compose version.

2024-12-15 16:08 UTC, paolorotolo approved these changes
Thanks again for your contributions @markoeltiger! Looks good!
I'll create a `-compose` branch temporarily to distinguish the WIP AppIntro from the stable one only based on views.

2024-12-15 22:19 UTC, merged

2024-12-17 15:48 UTC, markoeltiger commented
Thanks a lot @paolorotolo  we couldn't make it without your support and your feedback ! 
I think new compose branch idea is better yes .